name: RFRM Validation Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install numpy matplotlib

      - name: Run Recursive Fractal Model
        run: |
          python Recursive_Core/RFRM_Algorithms/core_rfrm.py
          ls -la  # Check if the output file exists

      - name: Upload Visualization
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: RFRM-visualization
          path: ./RFRM_output.png  # Ensure correct path

      - name: Download Visualization (Test Step)
        uses: actions/download-artifact@v4  # Updated from v3 to v4
        with:
          name: RFRM-visualization
          path: ./downloaded_artifacts
